### ISSUE TITLE
Merging of high-resolution data from CarbonLink and low-resolution data from Whisper leads to incorrect values until data is written to disk

### ISSUE THREAD

**Issue by Minnozz** [graphite-project/graphite-web#1391]
When a metric is requested for which not all data is written to Whisper (ie because writes are being throttled), the data from Whisper is merged with the data received from CarbonLink (carbon-cache). This data is then merged together (https://github.com/graphite-project/graphite-web/blob/12f2426066bbeaa97697f7c4d67821a6efdd9cbf/webapp/graphite/readers.py#L63).

When the data from Whisper is not in the highest/finest resolution defined in the storage schema, the data points from CarbonLink should be merged together according to the rules in storage-aggregation.conf, instead of sampling the higher-resolution data.

For instance, when the aggregation method is sum, the most recent part of the graph (for which the data comes from carbon-cache) has lower values than the part that comes from disk, because in the lower resolution from disk, multiple high-resolution values have been summed together.

**Comment by deniszh** [comment]
We faced similar issue. I thought it was fixed in https://github.com/graphite-project/graphite-web/commit/ff091fb4c766858bd6dcb28501eb1109995881d3 - merging will be done only when cache resolution equal with whisper resolution.

**Comment by Minnozz** [comment]
We are currently running 0.9.12; I will check it the problem still exists as soon as we upgrade to 0.9.14.

**Comment by obfuscurity** [comment]
Yes, I'm pretty sure this was fixed already in 0.9.14. Going to close this issue, but please let us know if you're still experiencing the problem after upgrading.
